# Generated by Django 4.2.23 on 2025-09-18 06:51

import apps.blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_skills'),
        ('category_skills', '0007_alter_session_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(upload_to=apps.blog.models.blog_images)),
                ('base_image', models.ImageField(upload_to=apps.blog.models.blog_images)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='accounts.user')),
                ('category', models.ForeignKey(default='Business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='category_skills.skillscategory')),
            ],
            options={
                'db_table': 'blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.blog_section_images)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blog')),
            ],
            options={
                'db_table': 'blogs_section',
                'ordering': ['-created_at'],
            },
        ),
    ]
