# Generated by Django 4.2.23 on 2025-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='base_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
