# Generated by Django 4.2.23 on 2025-09-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_base_image_remove_blog_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs_images/')),
                ('base', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('small', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog')),
            ],
            options={
                'db_table': 'blogs_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
