# Generated by Django 4.2.23 on 2025-09-22 05:07

import apps.blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_images_blogimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=apps.blog.models.blog_section_images),
            preserve_default=False,
        ),
    ]
