# Generated by Django 4.2.23 on 2025-09-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogsection_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='small',
            field=models.BooleanField(default=False),
        ),
    ]
