# Generated by Django 4.2.23 on 2025-09-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='university.department'),
        ),
        migrations.AlterField(
            model_name='university',
            name='level',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Professional', 'Professional')], default='Bachelors', max_length=25),
        ),
    ]
