# Generated by Django 4.2.23 on 2025-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_department_alter_university_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='department',
        ),
        migrations.AddField(
            model_name='university',
            name='departments',
            field=models.ManyToManyField(related_name='universities', to='university.department'),
        ),
    ]
