# Generated by Django 4.2.23 on 2025-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_remove_university_department_university_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='university',
            name='level',
        ),
        migrations.AddField(
            model_name='university',
            name='levels',
            field=models.ManyToManyField(related_name='universities', to='university.level'),
        ),
    ]
