# Generated by Django 4.2.23 on 2025-09-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_level_created_at_level_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityimages',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='university.university'),
        ),
    ]
