# Generated by Django 4.2.23 on 2025-09-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_skills'),
        ('category_skills', '0005_userskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('description', models.TextField(help_text='Message from requester to receiver', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When receiver responded to request', null=True)),
                ('receiver', models.ForeignKey(help_text='User who has the skill', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.user')),
                ('requester', models.ForeignKey(help_text='User who wants to learn the skill', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='accounts.user')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requests', to='category_skills.skills')),
            ],
            options={
                'verbose_name_plural': 'Skill Requests',
                'db_table': 'skill_requests',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'receiver', 'skill')},
            },
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Session description and agenda', max_length=1000)),
                ('session_type', models.CharField(choices=[('O', 'Online'), ('I', 'In-Person'), ('H', 'Hybrid')], default='O', max_length=1)),
                ('location', models.CharField(blank=True, help_text='Meeting location or online platform', max_length=300)),
                ('scheduled_date', models.DateTimeField(help_text='When the session is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Session duration in minutes')),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Completed'), ('CA', 'Cancelled'), ('P', 'Pending')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_rating', models.PositiveIntegerField(blank=True, help_text='Rating from teacher (1-5)', null=True)),
                ('learner_rating', models.PositiveIntegerField(blank=True, help_text='Rating from learner (1-5)', null=True)),
                ('teacher_feedback', models.TextField(blank=True, help_text='Feedback from teacher', max_length=500)),
                ('learner_feedback', models.TextField(blank=True, help_text='Feedback from learner', max_length=500)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='accounts.user')),
                ('request', models.ForeignKey(help_text='Associated request', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='category_skills.request')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sessions', to='category_skills.skills')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Skill Sessions',
                'db_table': 'skill_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
