# Generated by Django 4.2.23 on 2025-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0006_request_remove_userskills_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('A', 'Active'), ('C', 'Completed'), ('CA', 'Cancelled'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
